#!/usr/bin/perl
# ==============================================================
# Perl Scoreboard Parser & Error Summarizer
# Team 12 - BEVD205L Scripting Languages & Verification
# ==============================================================
# Usage:
#   perl parse_scoreboard.pl [results_dir]
#
# Reads all scoreboard_seed*.log and directed_*.log files in
# results/ (or a specified directory) and produces:
#   - Per-seed pass/fail summary
#   - Detailed failure report with TX data and error type
#   - Overall cumulative statistics
#   - HTML report: uart_report.html
# ==============================================================

use strict;
use warnings;
use File::Basename;
use POSIX qw(strftime);

# ---- Configuration ----
my $results_dir  = shift @ARGV // "results";
my $html_out     = "uart_report.html";
my $text_out     = "uart_summary.txt";

# ---- Data structures ----
my @all_failures;    # Array of hashrefs: {seed, tx, rx, parity, done}
my %seed_stats;      # seed => {pass, fail}
my $grand_pass  = 0;
my $grand_fail  = 0;

# ==============================================================
# Sub: parse_scoreboard_log
# Parses scoreboard_seed<N>.log files generated by the SV TB
# ==============================================================
sub parse_scoreboard_log {
    my ($file) = @_;
    my $seed = "directed";
    if ($file =~ /seed(\d+)/) { $seed = $1; }

    open(my $fh, '<', $file) or do {
        warn "Cannot open $file: $!\n";
        return;
    };

    $seed_stats{$seed} //= { pass => 0, fail => 0 };

    while (my $line = <$fh>) {
        chomp $line;
        next if $line =~ /^#/;    # Skip comment lines

        # Format: STATUS | TX=0xXX | RX=0xXX | parity_err=N | done=N
        if ($line =~ /^(PASS|FAIL)\s*\|\s*TX=(0x[0-9A-Fa-f]+)\s*\|\s*RX=(0x[0-9A-Fa-f]+)\s*\|\s*parity_err=(\d+)\s*\|\s*done=(\d+)/) {
            my ($status, $tx, $rx, $parity_err, $done) = ($1, $2, $3, $4, $5);

            if ($status eq 'PASS') {
                $seed_stats{$seed}{pass}++;
                $grand_pass++;
            } else {
                $seed_stats{$seed}{fail}++;
                $grand_fail++;

                # Classify failure type
                my $err_type;
                if ($parity_err) {
                    $err_type = "Parity Error";
                } elsif (!$done) {
                    $err_type = "No rx_done (Timeout / Framing)";
                } elsif ($tx ne $rx) {
                    $err_type = "Data Mismatch";
                } else {
                    $err_type = "Unknown";
                }

                push @all_failures, {
                    seed       => $seed,
                    tx         => $tx,
                    rx         => $rx,
                    parity_err => $parity_err,
                    done       => $done,
                    err_type   => $err_type,
                    source     => basename($file),
                };
            }
        }
    }
    close $fh;
}

# ==============================================================
# Sub: parse_transcript_log
# Parses directed_rx.log / directed_tx.log (transcript format)
# Lines like: [PASS] TC1: ... or [FAIL] TC1: ...
# ==============================================================
sub parse_transcript_log {
    my ($file, $label) = @_;
    open(my $fh, '<', $file) or do {
        warn "Cannot open $file: $!\n";
        return;
    };

    $seed_stats{$label} //= { pass => 0, fail => 0 };

    while (my $line = <$fh>) {
        chomp $line;
        if ($line =~ /^\[PASS\]/) {
            $seed_stats{$label}{pass}++;
            $grand_pass++;
        } elsif ($line =~ /^\[FAIL\]\s+(.+)/) {
            my $detail = $1;
            $seed_stats{$label}{fail}++;
            $grand_fail++;

            # Try to extract TX/RX from FAIL line
            my ($tx, $rx) = ("N/A", "N/A");
            $tx = $1 if $detail =~ /Expected=(0x[0-9A-Fa-f]+)/;
            $rx = $1 if $detail =~ /Got=(0x[0-9A-Fa-f]+)/;

            push @all_failures, {
                seed       => $label,
                tx         => $tx,
                rx         => $rx,
                parity_err => "?",
                done       => "?",
                err_type   => "Directed Test Failure",
                detail     => $detail,
                source     => basename($file),
            };
        }
    }
    close $fh;
}

# ==============================================================
# Main: Scan results directory
# ==============================================================
print "=" x 56 . "\n";
print " UART Scoreboard Parser - Team 12\n";
print " Results dir : $results_dir\n";
print " Generated   : " . strftime("%Y-%m-%d %H:%M:%S", localtime) . "\n";
print "=" x 56 . "\n\n";

die "Results directory '$results_dir' not found!\n"
    unless -d $results_dir;

# Parse directed logs
for my $label (qw(directed_rx directed_tx)) {
    my $f = "$results_dir/$label.log";
    if (-f $f) {
        print "Parsing directed log: $f\n";
        parse_transcript_log($f, $label);
    }
}

# Parse random scoreboard logs
for my $file (sort glob("$results_dir/scoreboard_seed*.log")) {
    print "Parsing scoreboard: $file\n";
    parse_scoreboard_log($file);
}

print "\n";

# ==============================================================
# Text Summary
# ==============================================================
open(my $txt, '>', $text_out) or die "Cannot write $text_out: $!\n";

my $now = strftime("%Y-%m-%d %H:%M:%S", localtime);

my @txt_lines = (
    "=" x 56,
    " UART VERIFICATION SUMMARY REPORT - Team 12",
    " Date: $now",
    "=" x 56,
    "",
    "PER-RUN BREAKDOWN:",
    "-" x 40,
);

for my $seed (sort keys %seed_stats) {
    my $p = $seed_stats{$seed}{pass};
    my $f = $seed_stats{$seed}{fail};
    my $t = $p + $f;
    my $pct = $t > 0 ? sprintf("%.1f%%", 100 * $p / $t) : "N/A";
    push @txt_lines, sprintf("  %-20s : PASS=%-4d FAIL=%-4d TOTAL=%-4d (%s)", $seed, $p, $f, $t, $pct);
}

push @txt_lines, (
    "-" x 40,
    sprintf("  %-20s : PASS=%-4d FAIL=%-4d TOTAL=%-4d", "GRAND TOTAL", $grand_pass, $grand_fail, $grand_pass + $grand_fail),
    "=" x 56,
    "",
);

if (@all_failures) {
    push @txt_lines, ("FAILURE DETAILS:", "-" x 40);
    my $n = 1;
    for my $f (@all_failures) {
        push @txt_lines, (
            sprintf("  [%02d] Run=%-15s Source=%s", $n, $f->{seed}, $f->{source}),
            sprintf("       TX=%-6s  RX=%-6s  Type=%s", $f->{tx}, $f->{rx}, $f->{err_type}),
        );
        push @txt_lines, sprintf("       Detail: %s", $f->{detail}) if exists $f->{detail};
        push @txt_lines, "";
        $n++;
    }
} else {
    push @txt_lines, "  ** No failures detected - All tests passed! **";
}

push @txt_lines, ("=" x 56, "");

for my $l (@txt_lines) {
    print "$l\n";
    print $txt "$l\n";
}
close $txt;
print "Text report saved to: $text_out\n";

# ==============================================================
# HTML Report
# ==============================================================
open(my $html, '>', $html_out) or die "Cannot write $html_out: $!\n";

my $pass_color  = "#2ecc71";
my $fail_color  = "#e74c3c";
my $total       = $grand_pass + $grand_fail;
my $pct_pass    = $total > 0 ? sprintf("%.1f", 100 * $grand_pass / $total) : 0;

print $html <<HTML;
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>UART Verification Report - Team 12</title>
<style>
  body        { font-family: 'Courier New', monospace; background:#1a1a2e; color:#e0e0e0; margin:2rem; }
  h1          { color:#00d4ff; border-bottom:2px solid #00d4ff; padding-bottom:0.5rem; }
  h2          { color:#a0c4ff; margin-top:2rem; }
  table       { border-collapse:collapse; width:100%; margin-top:1rem; }
  th          { background:#0d3b66; color:#fff; padding:0.6rem 1rem; text-align:left; }
  td          { padding:0.5rem 1rem; border-bottom:1px solid #333; }
  tr:hover    { background:#263860; }
  .pass       { color:$pass_color; font-weight:bold; }
  .fail       { color:$fail_color; font-weight:bold; }
  .metric     { display:inline-block; background:#0d3b66; border-radius:8px;
                padding:1rem 2rem; margin:0.5rem; text-align:center; }
  .metric-val { font-size:2.5rem; font-weight:bold; display:block; }
  .bar-wrap   { background:#333; border-radius:4px; height:24px; margin:1rem 0; }
  .bar-fill   { background:$pass_color; height:24px; border-radius:4px;
                width:${pct_pass}%; display:flex; align-items:center;
                padding-left:8px; font-weight:bold; font-size:0.9rem; }
  footer      { margin-top:3rem; color:#666; font-size:0.8rem; }
</style>
</head>
<body>
<h1>&#x1F4CB; UART Verification Report</h1>
<p>BEVD205L Scripting Languages &amp; Verification &mdash; Team 12 &mdash; $now</p>

<h2>Overall Results</h2>
<div>
  <div class="metric"><span class="metric-val pass">$grand_pass</span>PASS</div>
  <div class="metric"><span class="metric-val fail">$grand_fail</span>FAIL</div>
  <div class="metric"><span class="metric-val">$total</span>TOTAL</div>
  <div class="metric"><span class="metric-val">${pct_pass}%</span>Pass Rate</div>
</div>
<div class="bar-wrap">
  <div class="bar-fill">${pct_pass}%</div>
</div>

<h2>Per-Run Breakdown</h2>
<table>
  <tr><th>Run / Seed</th><th>PASS</th><th>FAIL</th><th>Total</th><th>Pass Rate</th></tr>
HTML

for my $seed (sort keys %seed_stats) {
    my $p   = $seed_stats{$seed}{pass};
    my $f   = $seed_stats{$seed}{fail};
    my $t   = $p + $f;
    my $pct = $t > 0 ? sprintf("%.1f%%", 100 * $p / $t) : "N/A";
    my $fc  = $f > 0 ? "fail" : "pass";
    print $html "<tr><td>$seed</td><td class=\"pass\">$p</td>"
              . "<td class=\"$fc\">$f</td><td>$t</td><td>$pct</td></tr>\n";
}

print $html "</table>\n";

if (@all_failures) {
    print $html "<h2>&#x26A0; Failure Details</h2>\n";
    print $html "<table>\n<tr><th>#</th><th>Run</th><th>TX Data</th>"
              . "<th>RX Data</th><th>Error Type</th><th>Source</th></tr>\n";
    my $n = 1;
    for my $f (@all_failures) {
        my $det = exists $f->{detail} ? " &mdash; $f->{detail}" : "";
        print $html "<tr><td>$n</td><td>$f->{seed}</td>"
                  . "<td>$f->{tx}</td><td>$f->{rx}</td>"
                  . "<td class=\"fail\">$f->{err_type}$det</td>"
                  . "<td>$f->{source}</td></tr>\n";
        $n++;
    }
    print $html "</table>\n";
} else {
    print $html "<h2 class=\"pass\">&#x2705; All Tests Passed!</h2>\n";
}

print $html <<HTML;
<footer>
  <p>Generated by parse_scoreboard.pl &mdash; Team 12</p>
  <p>Members: J Jonathan Gerard Joseph &bull; Nakul Kulkarni &bull; Purti Badole &bull; Tanay Ashwath</p>
</footer>
</body>
</html>
HTML

close $html;
print "HTML report saved to: $html_out\n";

print "\nDone. Failures: $grand_fail / $total\n";
exit($grand_fail > 0 ? 1 : 0);
